47 statistical parameters improvement
Tole-k/turbo-ml pull request #51
Opened 2024-10-26 00:21 UTC by Dawid64

Implemented meta features from paper: "Initializing bayesian hyperparameter optimization via meta-learning".
Additionally fixed preprocessing issue.

2024-10-26 22:43 UTC, Tole-k requested changes

2024-10-26 22:43 UTC, Tole-k commented on turbo_ml/turboml.py
when passing parameters to hpo tuner accesing via . doesnt work anymore and should be changed to [''] just like in turboml_experimental

2024-10-26 22:43 UTC, Tole-k commented on turbo_ml/meta_learning/meta_model/meta_model_search.py
You seem to blacklist NeuralNetworkModel, what's the reason behind it? is there some problem with it? (apart from optuna's inablity to tune it thoroughly enough, which would actually be a valid reason)

2024-10-27 15:45 UTC, Dawid64 commented on turbo_ml/meta_learning/meta_model/meta_model_search.py
This is due to inability of NNModel to autocomplete it's input, as it was the only model that needed additional user input and made could easily make problems that could not always be seen so easily (Kind of issue that can occur once per 100 runs which is the worst kind of issue)

2024-10-27 15:55 UTC, Dawid64 commented on turbo_ml/turboml.py
Should be solved in new commits

2024-10-27 16:04 UTC, adamtms commented on turbo_ml/meta_learning/dataset_parameters/sota.py
> +        num_patters = len(dataset)
Typo. num_patters instead of num_patterns

2024-10-27 19:28 UTC, Tole-k approved these changes

2024-10-27 20:28 UTC, merged